tasks:
  - name: install-dependencies
    init: |
      docker pull cassandra:4
      pip install -U cqlsh
      wget https://archive.apache.org/dist/cassandra/4.0.0/apache-cassandra-4.0.0-bin.tar.gz
      tar xzf apache-cassandra-4.0.0-bin.tar.gz
    command: | 
      docker run -p 9042:9042 -d cassandra:4
ports:
  - port: 9042
    onOpen: ignore  
github:
  prebuilds:
    main: true
vscode:
  extensions:
    - https://github.com/HadesArchitect/katapod/releases/download/0.3.6/katapod-0.3.6.vsix
